title: "Dakshina and Gina portfolio!"
description: >- # this means to ignore newlines until "baseurl:"
  This is our project for the MLH introduction hack. This is a
  template that you could use to create your portfolio
# Root directory for your portfolio. On GitHub Pages, this is the name of your repository.
baseurl: "/portfolio-template"
# Protocol + hostname for your portfolio. On GitHub Pages, this is https://yourusername.github.io
url: "https://mlh-fellowship.github.io" 
twitter_username: mlhacks
github_username: mlh-fellowship


sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
